version: '3.3'

services:
  database:
    image: mariadb
    environment:  # probably should have an actual username and password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "productiondb"

  pyarcade:
    image: pyarcade:rest_deploy
    environment:
      FLASK_ENV: "production"
    ports:
      - 5000:5000
    command: ["wait-for-it.sh", "database:3306", "-t", "60", "--", "gunicorn", "-w", "4", "--bind", "0.0.0.0:5000", "--reload", "pyarcade_rest:create_app()"]
